POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Diogo",
  "email": "diogomarciano40@gmail.com",
  "password": "rms1529589"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "diogomarciano40@gmail.com",
  "password": "rms1529589"
}

###
POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkaW9nb21hcmNpYW5vNDBAZ21haWwuY29tIiwiaWF0IjoxNzY2ODQzODE0LCJleHAiOjE3NjY5MzAyMTR9.LZePsKPsW5fPBXhEJ5M4aqAuvjqn1kyQSiPvArfbqhQ
Content-Type: application/json

{
  "title": "Estudar Node.js",
  "status": "pendente"
}

###
DELETE http://localhost:3000/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkaW9nb21hcmNpYW5vNDBAZ21haWwuY29tIiwiaWF0IjoxNzY2ODQzODE0LCJleHAiOjE3NjY5MzAyMTR9.LZePsKPsW5fPBXhEJ5M4aqAuvjqn1kyQSiPvArfbqhQ  
Content-Type: application/json

###
PUT http://localhost:3000/tasks/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkaW9nb21hcmNpYW5vNDBAZ21haWwuY29tIiwiaWF0IjoxNzY2ODQzODE0LCJleHAiOjE3NjY5MzAyMTR9.LZePsKPsW5fPBXhEJ5M4aqAuvjqn1kyQSiPvArfbqhQ
Content-Type: application/json
Accept: application/json

{
  "title": "Estudar Node.js",
  "status": "em andamento"
}

###
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkaW9nb21hcmNpYW5vNDBAZ21haWwuY29tIiwiaWF0IjoxNzY2ODQzODE0LCJleHAiOjE3NjY5MzAyMTR9.LZePsKPsW5fPBXhEJ5M4aqAuvjqn1kyQSiPvArfbqhQ